<?php
/**
 * Roll back the last monitoring status change (error protection).
 * POST: project_id, [admin_password]
 *
 * Any back-office role can open the monitoring page, but reverting is sensitive:
 *  - Super Admin / Admin: may revert directly (after the on-screen confirmation).
 *  - Staff: must supply a valid admin password to authorize the revert.
 */
require_once __DIR__ . '/../includes/helpers.php';
require_page('monitoring', true);
require_once __DIR__ . '/../includes/project_status.php';
header('Content-Type: application/json; charset=utf-8');

function rv_fail(string $m, int $c = 400): void
{
    http_response_code($c);
    echo json_encode(['ok' => false, 'error' => $m]);
    exit;
}

ensure_prev_status_column();
ensure_revert_codes_table();

$projectId  = (int) ($_POST['project_id'] ?? 0);
$revertCode = strtoupper(trim((string) ($_POST['revert_code'] ?? '')));
if ($projectId <= 0) rv_fail('Invalid request.');

$pdo = db();
$row = $pdo->prepare("SELECT * FROM projects WHERE id = ?");
$row->execute([$projectId]);
$project = $row->fetch();
if (!$project) rv_fail('Project not found.', 404);

// Target phase: the recorded previous status (exact undo) or, failing that, one
// phase back in the ordered sequence — so a wrongly-advanced project can always
// be corrected even if the change didn't go through monitoring.
$prev = $project['prev_status'] ?? null;
if ($prev === null || $prev === '' || !array_key_exists($prev, project_statuses())) {
    $idx = project_step_index($project['status']);
    if ($idx !== null && $idx > 0) {
        $phaseKeys = array_keys(project_phases());
        $prev = $phaseKeys[$idx - 1];
    } else {
        $prev = null;
    }
}
if ($prev === null || $prev === '') rv_fail('There is no earlier phase to revert to.');

// Authorization: Staff must provide a valid, unused revert code (generated by an
// admin in Settings). The code is consumed here on success. Super Admin / Admin
// may revert without a code.
$usedCodeId = 0;
if (!in_array(current_role(), ['Super Admin', 'Admin'], true)) {
    if ($revertCode === '') rv_fail('A revert authorization code is required. Ask an admin for one.', 403);
    // Codes are reusable until an admin revokes (deletes) them.
    $st = $pdo->prepare("SELECT id FROM revert_codes WHERE code = ? LIMIT 1");
    $st->execute([$revertCode]);
    $usedCodeId = (int) $st->fetchColumn();
    if ($usedCodeId <= 0) rv_fail('That authorization code is invalid or has been revoked.', 403);
}

$progressMap = [
    'quote_submitted' => 0, 'approved' => 10, 'production' => 30, 'mockup' => 45,
    'delivery' => 60, 'installation' => 75, 'quality_check' => 85, 'punchlist' => 92,
    'final_approval' => 97, 'completed' => 100,
];
$prevLabel = project_status_label($prev);
$progress  = $progressMap[$prev] ?? (int) $project['progress'];

try {
    // Revert and clear prev_status (single-step undo).
    $pdo->prepare("UPDATE projects SET status = ?, progress = ?, prev_status = NULL WHERE id = ?")
        ->execute([$prev, $progress, $projectId]);

    // Leaving 'completed' reopens the project — clear the completion window.
    if ($project['status'] === 'completed' && $prev !== 'completed') {
        $pdo->prepare("UPDATE projects SET completion_notified_at = NULL, client_confirmed_at = NULL WHERE id = ?")
            ->execute([$projectId]);
    }

    // Record the code's last use (it stays valid — reusable until revoked).
    if ($usedCodeId > 0) {
        $pdo->prepare("UPDATE revert_codes SET used_by = ?, used_at = NOW() WHERE id = ?")
            ->execute([current_user()['id'] ?? null, $usedCodeId]);
    }

    $who = current_user()['full_name'] ?? 'A staff member';
    add_project_update($projectId, "Status change reverted to \"{$prevLabel}\".", true);
    log_audit('Monitoring', "Reverted {$project['project_code']} to {$prevLabel}", "By {$who}");

    echo json_encode(['ok' => true, 'status' => $prev, 'label' => $prevLabel]);
} catch (Throwable $e) {
    rv_fail('Server error: ' . $e->getMessage(), 500);
}
